name: Build LaTeX Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: konstantin_tenman_resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v2
        with:
          name: Resume
          path: konstantin_tenman_resume.pdf
