name: Build LaTeX Resume

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: konstantin_tenman_resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: konstantin_tenman_resume.pdf
